spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      max-active: 100
      max-wait: 360000
      validation-query: select 1 from dual
      validation-interval: 10000
  profiles:
    active: ${spring_profile_active:local}

server:
  port: 18080

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.hf.Ac99Info

logging:
  config: classpath:logback-spring.xml

value:
  page:
    size: ${value_page_size:500}

elasticsearch:
  host: 10.85.94.57
  port: 19200
  connTimeout: 30000
  socketTimeout: 50000
  connectionRequestTimeout: 5000
  userName: elastic
  password: m4OhCvLfnrnLh6y9ZXsx


ali-yun:
  oss:
    endpoint: ${oss_endpoint:http://oss-hf-hangzhou-zjzwy01-d01-a.cloud-inner.zj.gov.hf/}
    access-key-id: ${oss_access-key-id:1hD08MPW6e98yoBF}
    access-key-secret: ${access-key-secret:wAVr22nKpCxF61WPb6AGXeHUk6VqfC}
    bucket-name: ${oss_bucket-name:yyfjcc-oss}

## 过滤器、拦截器需要的配置信息
exclude:
  webMvcPatterns:
    - /user/login/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /webjars/**
    - /js/**
  webMvcDomainHosts:
    - localhost
  csrfDomainHosts:
    - localhost
    - 127.0.0.1
    - 183.129.231.110
    - 192.168.206.203
  csrfPatternsApi:
    - /swagger-ui.html


graph:
  nebula:
    hosts: 10.85.158.128:8008
    max-conn: 1000
    username: root
    password: nebula