spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://183.129.231.110:62312/lsxxzj?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT
    username: taxdb
    password: taxdb
  redis:
    host: 10.85.94.57
    port: 6379
    database: 2
    password: EpsoftRedis2021