spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.207.191:1521/orcl
    username: ddm
    password: ddm
  redis:
    host: 10.85.94.57
    port: 6379
    database: 2
    password: EpsoftRedis2021